import type { Metadata } from "next";
import { Inter, Instrument_Sans } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
    subsets: ["latin"],
    variable: "--font-instrument-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${instrumentSans.variable} antialiased`}
      >
        <div
          className={`font-main bg-[url(/background.jpg)] w-full h-[600px] lg:h-[912px] transition-transform bg-cover`}
        >
          <NavBar />
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
